name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update
          apt-get install -y ca-certificates openssl uuid-dev make rsync ssh
      - uses: Bogdanp/setup-racket@v1.5
        with:
          architecture: 'x64'      # (x64 or x86), ignored on Linux
          distribution: 'full'  # or 'minimal'
          variant: 'CS'            # or 'CS' for Racket-on-Chez
          version: '8.0'           # or 'current' for the latest snapshot
          packages: 'darwin, rosette'
      - run: make site
      - run: ./rememberme.sh
      - name: Save ssh keys
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          mkdir /root/.ssh
          echo "$PRIVATE_KEY" > /root/.ssh/id_rsa
          echo "$PUBLIC_KEY" > /root/.ssh/id_rsa.pub
          chmod 600 /root/.ssh/id_rsa
          chmod 644 /root/.ssh/id_rsa.pub
          sha1sum /root/.ssh/*
      - run: ssh -o BatchMode=yes -o StrictHostKeyChecking=no root@racket-news.com echo "Hello RN!"
      - run: rsync -avz --delete public/ root@racket-news.com:/var/www/racket-news.com/
